# The Docker image that will be used to build your app
image: node:lts

# Functions that should be executed before the build script is run
before_script:
  - apt-get update && apt-get install -y zip   # Install zip to zip the dist folder
  - npm ci
  - npm run makeJson
  - node tasks/build_prepare.js
  - ./node_modules/.bin/tsc -p tsconfig-tasks.json
  - node tmp/tasks/build_json.js
  - node tmp/tasks/build_pdf.js
  - ./node_modules/.bin/tsc -p tsconfig-tasks.json
  - node tmp/tasks/build_json.js

# Build the project and zip the dist/ folder
build:
  stage: build
  script:
    - npx vite build               # Build the project using Vite
    - zip -r dist.zip dist/ --exclude \*.map  # Zip the dist folder, excluding .map files
  artifacts:
    paths:
      - dist.zip                    # Upload the zipped dist folder as an artifact
  rules:
    # Only run this job for commits on the default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

# Pages job to deploy the unzipped artifacts
pages:
  stage: deploy
  script:
    - unzip dist.zip                # Unzip the artifact
  artifacts:
    paths:
      - dist/                       # The unzipped dist folder to be deployed
  rules:
    # Only run this job for commits on the default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  publish: dist