export const dictionnaireEAM = {
  eam_specialite_2025_06_sujet0v1_1: {
    annee: '2025',
    lieu: 'Spécialité sujet0v1',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['QCM'],
  },
  eam_specialite_2025_06_sujet0v1_2: {
    annee: '2025',
    lieu: 'Spécialité sujet0v1',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Produit scalaire'],
  },
  eam_specialite_2025_06_sujet0v1_3: {
    annee: '2025',
    lieu: 'Spécialité sujet0v1',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Second degré', 'Dérivation', 'Suites'],
  },
  eam_specialite_2025_06_sujet0v2_1: {
    annee: '2025',
    lieu: 'Spécialité sujet0v2',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['QCM'],
  },
  eam_specialite_2025_06_sujet0v2_2: {
    annee: '2025',
    lieu: 'Spécialité sujet0v2',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Suites'],
  },
  eam_specialite_2025_06_sujet0v2_3: {
    annee: '2025',
    lieu: 'Spécialité sujet0v2',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Second degré', 'Dérivation', 'Exponentielle'],
  },
  eam_specifique_2025_06_sujet0v1_1: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v1',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['QCM'],
  },
  eam_specifique_2025_06_sujet0v1_2: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v1',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Suites', 'Pourcentages (évolutions)'],
  },
  eam_specifique_2025_06_sujet0v1_3: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v1',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ["Analyse de l'information", 'Probabilités'],
  },
  eam_specifique_2025_06_sujet0v1_4: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v1',
    mois: 'Juin',
    numeroInitial: '4',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Croissance linéaire', 'Modélisation'],
  },
  eam_specifique_2025_06_sujet0v2_1: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v2',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['QCM'],
  },
  eam_specifique_2025_06_sujet0v2_2: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v2',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Suites'],
  },
  eam_specifique_2025_06_sujet0v2_3: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v2',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Probabilités'],
  },
  eam_specifique_2025_06_sujet0v3_1: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v3',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['QCM'],
  },
  eam_specifique_2025_06_sujet0v3_2: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v3',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Suites'],
  },
  eam_specifique_2025_06_sujet0v3_3: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v3',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Probabilités'],
  },
  eam_specifique_2025_06_sujet0v3_4: {
    annee: '2025',
    lieu: 'Tronc commun sujet0v3',
    mois: 'Juin',
    numeroInitial: '4',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Probabilités', 'Vrai/Faux', 'Exponentielle'],
  },
  eam_technologique_2025_06_sujet0v1_1: {
    annee: '2025',
    lieu: 'Technologique sujet0v1',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['QCM'],
  },
  eam_technologique_2025_06_sujet0v1_2: {
    annee: '2025',
    lieu: 'Technologique sujet0v1',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['Suites'],
  },
  eam_technologique_2025_06_sujet0v1_3: {
    annee: '2025',
    lieu: 'Technologique sujet0v1',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['Dérivation'],
  },
  eam_technologique_2025_06_sujet0v1_4: {
    annee: '2025',
    lieu: 'Technologique sujet0v1',
    mois: 'Juin',
    numeroInitial: '4',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['Vrai/Faux', 'Probabilités'],
  },
  eam_technologique_2025_06_sujet0v2_1: {
    annee: '2025',
    lieu: 'Technologique sujet0v2',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['QCM'],
  },
  eam_technologique_2025_06_sujet0v2_2: {
    annee: '2025',
    lieu: 'Technologique sujet0v2',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['VRAI/Faux', 'Suites', 'Probabilités', 'Second degré'],
  },
  eam_technologique_2025_06_sujet0v2_3: {
    annee: '2025',
    lieu: 'Technologique sujet0v2',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['Second degré'],
  },
  eam_technologique_2025_06_sujet0v2_4: {
    annee: '2025',
    lieu: 'Technologique sujet0v2',
    mois: 'Juin',
    numeroInitial: '4',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['Probabilités', 'Suites'],
  },
  eam_specialite_2026_06_ameriquenord_1: {
    annee: '2026',
    lieu: 'Spécialité Amérique du Nord',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Probabilités', 'Variables aléatoires'],
  },
  eam_specialite_2026_06_ameriquenord_2: {
    annee: '2026',
    lieu: 'Spécialité Amérique du Nord',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Suites', 'Python'],
  },
  eam_specialite_2026_06_ameriquenord_3: {
    annee: '2026',
    lieu: 'Spécialité Amérique du Nord',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Exponentielle', 'Dérivation'],
  },
  eam_specifique_2026_06_ameriquenord_1: {
    annee: '2026',
    lieu: 'Spécifique Amérique du Nord',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Suites', 'Tableur'],
  },
  eam_specifique_2026_06_ameriquenord_2: {
    annee: '2026',
    lieu: 'Spécifique Amérique du Nord',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Probabilités'],
  },
  eam_specifique_2026_06_ameriquenord_3: {
    annee: '2026',
    lieu: 'Spécifique Amérique du Nord',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Dérivation', 'Second degré'],
  },
  eam_specialite_2026_06_etrangers_1: {
    annee: '2026',
    lieu: 'Spécialité Centres étrangers',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Suites', 'Python'],
  },
  eam_specialite_2026_06_etrangers_2: {
    annee: '2026',
    lieu: 'Spécialité Centres étrangers',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Produit scalaire'],
  },
  eam_specialite_2026_06_etrangers_3: {
    annee: '2026',
    lieu: 'Spécialité Centres étrangers',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Dérivation'],
  },
  eam_specialite_2026_06_etrangers_automatismes: {
    annee: '2026',
    lieu: 'Spécialité Centres étrangers',
    mois: 'Juin',
    numeroInitial: 'automatismes',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Automatismes'],
  },
  eam_technologique_2026_06_etrangers_1: {
    annee: '2026',
    lieu: 'Centres étrangers',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['Vrai/Faux', 'Suites', 'Probabilités'],
  },
  eam_technologique_2026_06_etrangers_2: {
    annee: '2026',
    lieu: 'Centres étrangers',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['Dérivation', 'Troisième degré'],
  },
  eam_technologique_2026_06_etrangers_automatismes: {
    annee: '2026',
    lieu: 'Centres étrangers',
    mois: 'Juin',
    numeroInitial: 'automatismes',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: ['Automatismes'],
  },
  eam_specialite_2026_06_ameriquenord_automatismes: {
    annee: '2026',
    lieu: 'Spécialité Amérique du Nord',
    mois: 'Juin',
    numeroInitial: 'automatismes',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: ['Automatismes'],
  },
  eam_specifique_2026_06_ameriquenord_automatismes: {
    annee: '2026',
    lieu: 'Spécifique Amérique du Nord',
    mois: 'Juin',
    numeroInitial: 'automatismes',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: ['Automatismes'],
  },

  eam_specifique_2026_06_etrangers_1: {
    annee: '2026',
    lieu: 'Spécifique Centres étrangers',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2026_06_etrangers_2: {
    annee: '2026',
    lieu: 'Spécifique Centres étrangers',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2026_06_etrangers_3: {
    annee: '2026',
    lieu: 'Spécifique Centres étrangers',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2026_06_etrangers_automatismes: {
    annee: '2026',
    lieu: 'Spécifique Centres étrangers',
    mois: 'Juin',
    numeroInitial: 'automatismes',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
}
